#! /bin/bash
# @sourcify_start
set -euo pipefail
# @sourcify_end

VERSION="0.3.0"
SCRIPT_URL="https://raw.githubusercontent.com/simonrelet/scripts/sourcify-latest/bin/sourcify.sh"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
WARNING_COMMENT="$(cat << EOF
# THIS FILE WAS GENERATED BY SOURCIFY $VERSION, DO NOT MAKE CHANGES IN IT.
#
# If an update is required please modify the source files and re-sourcify it.
# For more information please refer to the documentation:
# https://github.com/simonrelet/scripts/tree/sourcify-v$VERSION/sourcify/
EOF
)"
